/**
 * Returns the static URL for a card's PNG file.
 * Files live in public/cards/{suitId}-{value}[-c].png,
 * pre-generated by scripts/generate-cards.js at build time.
 */

const SUIT_ID = { '♠': 'S', '♣': 'C', '♥': 'H', '♦': 'D' };

export function cardToSvgUrl(card, crystallized = false) {
  const suitId = SUIT_ID[card.suit] ?? 'S';
  const suffix = crystallized ? '-c' : '';
  return `/cards/${suitId}-${card.value}${suffix}.png`;
}
